# Generated by Django 5.2.5 on 2025-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0031_remove_packageimage_package_remove_package_gallery_and_more'),
    ]

    operations = [
        # Skip all operations - table may already be renamed or doesn't exist
        # RenameIndex - index doesn't exist
        # RemoveField city - field may not exist  
        # AlterModelTable - table may already be renamed
        # Empty operations list - migration will be marked as applied without doing anything
    ]

