"""
Fix script for migration 0032 on server
This script creates a safe migration file that skips problematic operations
"""

MIGRATION_CONTENT = '''# Generated by Django 5.2.5 on 2025-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0031_remove_packageimage_package_remove_package_gallery_and_more'),
    ]

    operations = [
        # Skip RenameIndex - index doesn't exist
        # Skip RemoveField city - field may not exist
        # Only keep table rename if needed
        migrations.AlterModelTable(
            name='salesrepresentative',
            table='travels_executive',
        ),
    ]
'''

print("=" * 60)
print("FIX FOR SERVER MIGRATION 0032")
print("=" * 60)
print("\n1. Server पर जाएं और निम्नलिखित file edit करें:")
print("   /var/www/safarzonetravels/travels/migrations/0032_*.py")
print("\n2. File का content replace करें नीचे दिए गए content से:\n")
print(MIGRATION_CONTENT)
print("\n" + "=" * 60)
print("ALTERNATIVE: Manual Fix")
print("=" * 60)
print("\nअगर file edit करना मुश्किल है, तो:")
print("1. Server पर SSH करें")
print("2. Run करें:")
print("   cd /var/www/safarzonetravels")
print("   python manage.py migrate travels 0031 --fake")
print("3. फिर problematic migration को skip करें:")
print("   python manage.py migrate --fake travels 0032")
print("\n" + "=" * 60)

