# Generated by Django 5.2.5 on 2025-11-06 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='package title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('destination', models.CharField(max_length=200, verbose_name='destination')),
                ('short_description', models.TextField(max_length=200, verbose_name='short description')),
                ('description', models.TextField(verbose_name='detailed description')),
                ('duration_days', models.PositiveIntegerField(verbose_name='duration in days')),
                ('duration_nights', models.PositiveIntegerField(verbose_name='duration in nights')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='starting price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percentage')),
                ('package_type', models.CharField(choices=[('vacation', 'Vacation Package'), ('honeymoon', 'Honeymoon Package'), ('adventure', 'Adventure Package'), ('cruise', 'Cruise Package'), ('pilgrimage', 'Pilgrimage Package'), ('custom', 'Custom Package')], default='vacation', max_length=20, verbose_name='package type')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('itinerary', models.JSONField(blank=True, default=list, help_text='List of daily activities in JSON format', verbose_name='itinerary')),
                ('inclusions', models.JSONField(blank=True, default=list, help_text="List of what's included in the package", verbose_name='inclusions')),
                ('exclusions', models.JSONField(blank=True, default=list, help_text="List of what's not included in the package", verbose_name='exclusions')),
                ('main_image', models.ImageField(upload_to='packages/main/', verbose_name='main image')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='meta keywords')),
            ],
            options={
                'verbose_name': 'travel package',
                'verbose_name_plural': 'travel packages',
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='user type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('can_manage_bookings', 'Can manage bookings'), ('can_manage_routes', 'Can manage routes'), ('can_view_reports', 'Can view reports')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(editable=False, max_length=12, unique=True, verbose_name='booking reference')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base fare')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='currency')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('notes', models.TextField(blank=True, help_text='Internal notes not visible to the customer', verbose_name='internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, verbose_name='gender')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='passport number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='passport expiry')),
                ('nationality', models.CharField(default='Indian', max_length=100, verbose_name='nationality')),
                ('passenger_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child (2-12 years)'), ('infant', 'Infant (0-2 years)'), ('senior', 'Senior Citizen (60+ years)')], default='adult', max_length=10, verbose_name='passenger type')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('seat_preference', models.CharField(blank=True, max_length=20, verbose_name='seat preference')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='travels.booking')),
            ],
            options={
                'verbose_name': 'passenger',
                'verbose_name_plural': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travels.package')),
            ],
            options={
                'verbose_name': 'package image',
                'verbose_name_plural': 'package images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='package_gallery', to='travels.packageimage'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g., Mumbai to Delhi Express', max_length=200, verbose_name='route name')),
                ('from_location', models.CharField(max_length=100, verbose_name='from')),
                ('to_location', models.CharField(max_length=100, verbose_name='to')),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('cruise', 'Cruise')], default='flight', max_length=20, verbose_name='transport type')),
                ('carrier_number', models.CharField(max_length=20, unique=True, verbose_name='flight/bus/train number')),
                ('departure_time', models.TimeField(verbose_name='departure time')),
                ('arrival_time', models.TimeField(verbose_name='arrival time')),
                ('duration', models.DurationField(help_text='Format: HH:MM:SS', verbose_name='duration')),
                ('route_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20, verbose_name='route type')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='JSON of available amenities (e.g., {"wifi": true, "meals": true})', verbose_name='amenities')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'ordering': ['from_location', 'to_location', 'departure_time'],
                'unique_together': {('from_location', 'to_location', 'carrier_number', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateField(verbose_name='departure date')),
                ('arrival_date', models.DateField(verbose_name='arrival date')),
                ('total_seats', models.PositiveIntegerField(default=50, verbose_name='total seats')),
                ('available_seats', models.PositiveIntegerField(default=50, verbose_name='available seats')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='travels.route')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
                'ordering': ['departure_date', 'route__departure_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='travels.schedule', verbose_name='schedule'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_type', models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('passport', 'Passport'), ('voter', 'Voter ID'), ('driving', 'Driving License'), ('other', 'Other')], help_text='Type of government-issued ID', max_length=20, verbose_name='ID type')),
                ('id_number', models.CharField(blank=True, help_text='ID number of the selected ID type', max_length=50, verbose_name='ID number')),
                ('full_name', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(help_text='12-digit Aadhar number', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['slug'], name='package_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_featured'], name='package_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['package_type'], name='package_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('route', 'departure_date')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='booking_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='booking_payment_status_idx'),
        ),
    ]
