# Generated by Django 5.2.5 on 2025-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_otpverification_userprofile_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['email', 'is_verified'], name='otp_email_idx'),
        ),
    ]
