# Generated by Django 5.2.5 on 2025-11-18 19:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance')),
                ('is_active', models.BooleanField(default=False, help_text='Only admin can enable/disable wallet access', verbose_name='active')),
                ('max_balance', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum balance limit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('recharge', 'Recharge'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Admin Adjustment')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credit, negative for debit', max_digits=10, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance after')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reference_id', models.CharField(blank=True, help_text='Booking reference, payment ID, etc.', max_length=100, null=True, verbose_name='reference ID')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='travels.wallet')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_transaction_idx')],
            },
        ),
    ]
