# Generated by Django 5.2.5 on 2025-11-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpassenger',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Master', 'Master')], default='Mr', max_length=10, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_document_pdf',
            field=models.FileField(blank=True, help_text='Upload your ID document (Aadhar, Passport, etc.) as PDF', null=True, upload_to='user_documents/id/', verbose_name='ID Document PDF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Upload any other relevant documents as PDF', null=True, upload_to='user_documents/other/', verbose_name='Other Documents PDF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_pdf',
            field=models.FileField(blank=True, help_text='Upload your passport copy as PDF', null=True, upload_to='user_documents/passport/', verbose_name='Passport PDF'),
        ),
        migrations.AlterField(
            model_name='bookingpassenger',
            name='passenger_type',
            field=models.CharField(choices=[('adult', 'Adult (12+ years)'), ('child', 'Child (2-11 years)'), ('infant', 'Infant (0-2 years)'), ('senior', 'Senior Citizen (60+ years)')], default='adult', max_length=10, verbose_name='passenger type'),
        ),
    ]
