# Generated by Django 5.2.5 on 2025-11-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_bookingpassenger_title_userprofile_id_document_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='arrival_terminal',
            field=models.CharField(blank=True, help_text='Terminal number/name for arrival (e.g., T1, T2, Terminal A)', max_length=20, verbose_name='arrival terminal'),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_terminal',
            field=models.CharField(blank=True, help_text='Terminal number/name for departure (e.g., T1, T2, Terminal A)', max_length=20, verbose_name='departure terminal'),
        ),
        migrations.AddField(
            model_name='route',
            name='is_non_refundable',
            field=models.BooleanField(default=False, help_text='Mark this route as non-refundable', verbose_name='non-refundable'),
        ),
    ]
