# Generated by Django 5.2.5 on 2025-11-18 20:06

from django.db import migrations, models


def set_default_terminals(apps, schema_editor):
    """Set default terminal values for existing routes that have empty terminals"""
    Route = apps.get_model('travels', 'Route')
    Route.objects.filter(departure_terminal='').update(departure_terminal='T1')
    Route.objects.filter(arrival_terminal='').update(arrival_terminal='T1')


def reverse_set_default_terminals(apps, schema_editor):
    """Reverse migration - set terminals back to empty"""
    # This is a no-op as we can't determine which were originally empty
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_route_arrival_terminal_route_departure_terminal_and_more'),
    ]

    operations = [
        # First, set default values for existing records
        migrations.RunPython(set_default_terminals, reverse_set_default_terminals),
        # Then, make the fields required
        migrations.AlterField(
            model_name='route',
            name='arrival_terminal',
            field=models.CharField(help_text='Terminal number/name for arrival (e.g., T1, T2, Terminal A)', max_length=20, verbose_name='arrival terminal'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_terminal',
            field=models.CharField(help_text='Terminal number/name for departure (e.g., T1, T2, Terminal A)', max_length=20, verbose_name='departure terminal'),
        ),
    ]
