# Generated by Django 5.2.5 on 2025-11-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_alter_route_arrival_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_schedule',
            field=models.ForeignKey(blank=True, help_text='Return flight schedule for round trip bookings', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_bookings', to='travels.schedule', verbose_name='return schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return')], default='one_way', max_length=20, verbose_name='trip type'),
        ),
    ]
