# Generated by Django 5.2.5 on 2025-11-20 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_booking_return_schedule_booking_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='adult_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fare for adults (12+ years). If not set, uses base price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='adult fare (12+ years)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='child_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fare for children (2-11 years). Typically around ₹4000. Child gets a seat.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='child fare (2-11 years)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='infant_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Fare for infants (0-2 years). Typically around ₹4000. Infant travels on mother's lap, no seat.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='infant fare (0-2 years)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price (used as default adult fare if adult_fare is not set)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
