# Generated by Django 5.2.5 on 2025-11-25 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_schedule_adult_fare_schedule_child_fare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='reference ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='contact name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='company name')),
                ('origin', models.CharField(max_length=100, verbose_name='origin')),
                ('destination', models.CharField(max_length=100, verbose_name='destination')),
                ('departure_date', models.DateField(verbose_name='departure date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='return date')),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return')], default='one_way', max_length=20, verbose_name='trip type')),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20, verbose_name='travel class')),
                ('number_of_passengers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='number of passengers')),
                ('adults', models.PositiveIntegerField(default=0, verbose_name='adults')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='children')),
                ('infants', models.PositiveIntegerField(default=0, verbose_name='infants')),
                ('special_requirements', models.TextField(blank=True, help_text='Dietary requirements, wheelchair assistance, etc.', verbose_name='special requirements')),
                ('additional_notes', models.TextField(blank=True, verbose_name='additional notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use', verbose_name='admin notes')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group request',
                'verbose_name_plural': 'group requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='group_request_idx'), models.Index(fields=['status', 'created_at'], name='group_request_status_idx')],
            },
        ),
    ]
