# Generated by Django 5.2.5 on 2025-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('travels', '0012_grouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique client identifier assigned on registration', max_length=20, null=True, unique=True, verbose_name='client ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['client_id'], name='user_client_id_idx'),
        ),
    ]
