# Generated by Django 5.2.5 on 2025-11-25 19:16

from django.db import migrations
import random
import string


def generate_client_id():
    """Generate a unique random client ID"""
    while True:
        random_part = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
        client_id = f'SZ-{random_part}'
        return client_id


def populate_client_ids(apps, schema_editor):
    """Populate client_id for existing users"""
    User = apps.get_model('travels', 'User')
    existing_ids = set()
    
    for user in User.objects.filter(client_id__isnull=True):
        # Generate unique client ID
        while True:
            client_id = generate_client_id()
            if client_id not in existing_ids and not User.objects.filter(client_id=client_id).exists():
                existing_ids.add(client_id)
                user.client_id = client_id
                user.save(update_fields=['client_id'])
                break


def reverse_populate_client_ids(apps, schema_editor):
    """Reverse migration - clear client IDs"""
    User = apps.get_model('travels', 'User')
    User.objects.all().update(client_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_user_client_id_user_user_client_id_idx'),
    ]

    operations = [
        migrations.RunPython(populate_client_ids, reverse_populate_client_ids),
    ]
