# Generated by Django 5.2.7 on 2025-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_remove_aadhar_add_title_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your company/personal logo (Optional)', null=True, upload_to='user_documents/logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_card',
            field=models.ImageField(help_text='Upload your Aadhar card image (Required)', upload_to='user_documents/aadhar/', verbose_name='Aadhar Card'),
        ),
    ]
