# Generated by Django 5.2.5 on 2025-12-02 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0018_userprofile_logo_alter_userprofile_aadhar_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.CreateModel(
            name='CashBalanceWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance')),
                ('max_balance', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum balance limit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balance_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Balance Wallet',
                'verbose_name_plural': 'Cash Balance Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('recharge', 'Recharge'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credit, negative for debit', max_digits=10, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance after')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reference_id', models.CharField(blank=True, help_text='Booking reference, payment ID, etc.', max_length=100, null=True, verbose_name='reference ID')),
                ('cash_balance_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='travels.cashbalancewallet')),
            ],
            options={
                'verbose_name': 'Cash Balance Transaction',
                'verbose_name_plural': 'Cash Balance Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ODWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance')),
                ('is_active', models.BooleanField(default=False, help_text='Only admin can enable/disable OD wallet access', verbose_name='active')),
                ('max_balance', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum balance limit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='od_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OD Wallet',
                'verbose_name_plural': 'OD Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ODWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('recharge', 'Admin Recharge'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Admin Adjustment')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credit, negative for debit', max_digits=10, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance after')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reference_id', models.CharField(blank=True, help_text='Booking reference, payment ID, etc.', max_length=100, null=True, verbose_name='reference ID')),
                ('od_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='travels.odwallet')),
            ],
            options={
                'verbose_name': 'OD Wallet Transaction',
                'verbose_name_plural': 'OD Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.AddIndex(
            model_name='cashbalancetransaction',
            index=models.Index(fields=['cash_balance_wallet', 'created_at'], name='cash_balance_transaction_idx'),
        ),
        migrations.AddIndex(
            model_name='odwallettransaction',
            index=models.Index(fields=['od_wallet', 'created_at'], name='od_wallet_transaction_idx'),
        ),
    ]
