# Generated by Django 5.2.5 on 2025-12-02 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0019_remove_wallettransaction_wallet_cashbalancewallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(help_text='Name of the package (e.g., Thailand, Dubai, Singapore, Bali, Vietnam)', max_length=200, verbose_name='package name')),
                ('destination', models.CharField(max_length=200, verbose_name='destination')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='travel date')),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='number of people')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use', verbose_name='admin notes')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated amount')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_applications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Package Application',
                'verbose_name_plural': 'Package Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='package_application_idx'), models.Index(fields=['status', 'created_at'], name='package_application_status_idx'), models.Index(fields=['package_name'], name='package_application_name_idx')],
            },
        ),
    ]
