# Generated by Django 5.2.5 on 2025-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0020_packageapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(help_text='Contact number', max_length=20, verbose_name='phone number')),
                ('city', models.CharField(help_text='Place/City of executive', max_length=100, verbose_name='city')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which executives are displayed', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executives',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='executive_active_idx')],
            },
        ),
    ]
