# Generated by Django 5.2.5 on 2025-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_executive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhar_card',
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Account approval status - user can login only after approval', verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_card_back',
            field=models.ImageField(blank=True, help_text='Upload back side of your Aadhar card (Required)', null=True, upload_to='user_documents/aadhar/back/', verbose_name='Aadhar Card Back'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_card_front',
            field=models.ImageField(blank=True, help_text='Upload front side of your Aadhar card (Required)', null=True, upload_to='user_documents/aadhar/front/', verbose_name='Aadhar Card Front'),
        ),
        migrations.CreateModel(
            name='Umrah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('duration', models.CharField(choices=[('14', '14 Days'), ('20', '20 Days')], default='14', max_length=10, verbose_name='Duration')),
                ('preferred_date', models.DateField(verbose_name='Preferred Travel Date')),
                ('number_of_passengers', models.PositiveIntegerField(default=1, verbose_name='Number of Passengers')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests or Requirements')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reference_id', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Reference ID')),
            ],
            options={
                'verbose_name': 'Umrah Application',
                'verbose_name_plural': 'Umrah Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='umrah_status_idx'), models.Index(fields=['duration', 'preferred_date'], name='umrah_duration_date_idx')],
            },
        ),
    ]
