# Generated by Django 5.2.5 on 2025-12-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0022_remove_userprofile_aadhar_card_user_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpassenger',
            name='pnr',
            field=models.CharField(blank=True, editable=False, help_text='Passenger Name Record - automatically assigned from stock during booking', max_length=10, null=True, unique=True, verbose_name='PNR'),
        ),
        migrations.CreateModel(
            name='PNRStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pnr', models.CharField(help_text='Passenger Name Record - unique identifier for each passenger', max_length=10, unique=True, verbose_name='PNR')),
                ('is_assigned', models.BooleanField(default=False, help_text='Whether this PNR has been assigned to a passenger', verbose_name='assigned')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='assigned at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pnr', to='travels.bookingpassenger', verbose_name='assigned to passenger')),
            ],
            options={
                'verbose_name': 'PNR Stock',
                'verbose_name_plural': 'PNR Stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pnr'], name='pnr_stock_pnr_idx'), models.Index(fields=['is_assigned'], name='pnr_stock_assigned_idx')],
            },
        ),
    ]
