# Generated by Django 5.2.5 on 2025-12-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0023_bookingpassenger_pnr_pnrstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnrstock',
            options={'ordering': ['route', '-created_at'], 'verbose_name': 'PNR Stock', 'verbose_name_plural': 'PNR Stock'},
        ),
        migrations.AddField(
            model_name='pnrstock',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Route for which this PNR is valid. PNR can only be assigned to passengers booking this route.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_stock', to='travels.route', verbose_name='route'),
        ),
        migrations.AlterUniqueTogether(
            name='pnrstock',
            unique_together={('pnr', 'route')},
        ),
        migrations.AddIndex(
            model_name='pnrstock',
            index=models.Index(fields=['route', 'is_assigned'], name='pnr_stock_route_assigned_idx'),
        ),
    ]
