# Generated by Django 5.2.5 on 2025-12-09 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0024_alter_pnrstock_options_pnrstock_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='airline_name',
            field=models.CharField(blank=True, help_text='E.g., Indigo, Air India, SpiceJet, Vistara, etc.', max_length=100, verbose_name='airline/flight company name'),
        ),
        migrations.AddField(
            model_name='umrah',
            name='passport_size_photo',
            field=models.ImageField(blank=True, help_text='Upload passport size photo (Required)', null=True, upload_to='umrah/passport_photos/', verbose_name='Passport Size Photo'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SAVE20, FLAT500)', max_length=50, unique=True, verbose_name='coupon code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount value')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum booking amount required to use this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum purchase')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage coupons). Leave blank for no limit.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum discount')),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from this date/time', verbose_name='valid from')),
                ('valid_to', models.DateTimeField(help_text='Coupon valid until this date/time', verbose_name='valid to')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active', verbose_name='active')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used. Leave blank for unlimited.', null=True, verbose_name='usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used', verbose_name='used count')),
                ('description', models.TextField(blank=True, help_text='Description of the coupon (visible to users)', verbose_name='description')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='coupon_code_idx'), models.Index(fields=['is_active'], name='coupon_active_idx')],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='travels.coupon', verbose_name='coupon'),
        ),
    ]
