# Generated by Django 5.2.5 on 2025-12-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0025_route_airline_name_umrah_passport_size_photo_coupon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbalancetransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Balance History Detail', 'verbose_name_plural': 'Balance History Details'},
        ),
    ]
