# Generated by Django 5.2.5 on 2025-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0026_alter_cashbalancetransaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique agency identifier assigned on registration', max_length=20, null=True, unique=True, verbose_name='Agency ID'),
        ),
    ]
