# Generated by Django 5.2.5 on 2025-12-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0027_alter_user_client_id'),
    ]

    operations = [
        # Rename Executive model to SalesRepresentative (keeps same table)
        migrations.RenameModel(
            old_name='Executive',
            new_name='SalesRepresentative',
        ),
        # Update model options
        migrations.AlterModelOptions(
            name='salesrepresentative',
            options={
                'verbose_name': 'Sales Representative',
                'verbose_name_plural': 'Sales Representatives',
                'ordering': ['display_order', 'name']
            },
        ),
        # Update display_order help text
        migrations.AlterField(
            model_name='salesrepresentative',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which sales representatives are displayed', verbose_name='display order'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pnr',
            field=models.CharField(blank=True, default='', help_text='Passenger Name Record - same for all passengers on this flight on this date', max_length=10, verbose_name='PNR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingpassenger',
            name='pnr',
            field=models.CharField(blank=True, editable=False, help_text='Passenger Name Record - same for all passengers on same flight and date', max_length=10, null=True, verbose_name='PNR'),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_representative',
            field=models.ForeignKey(blank=True, help_text='Assigned sales representative for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='travels.salesrepresentative', verbose_name='Sales Representative'),
        ),
    ]
