# Generated by Django 5.2.5 on 2025-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0028_salesrepresentative_delete_executive_schedule_pnr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pnr',
            field=models.CharField(blank=True, db_index=True, help_text='Passenger Name Record - same for all passengers on this flight on this date', max_length=10, verbose_name='PNR'),
        ),
    ]
