# Generated by Django 5.2.5 on 2025-12-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0030_change_model_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageimage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='gallery',
        ),
        migrations.AlterUniqueTogether(
            name='pnrstock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pnrstock',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='pnrstock',
            name='route',
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
        migrations.DeleteModel(
            name='PNRStock',
        ),
    ]
