# Generated by Django 5.2.5 on 2025-12-14 01:13

from django.db import migrations, models
from django.core.validators import MinValueValidator
from decimal import Decimal


def migrate_price_to_adult_fare(apps, schema_editor):
    """Migrate existing price to adult_fare if adult_fare is null"""
    Schedule = apps.get_model('travels', 'Schedule')
    for schedule in Schedule.objects.all():
        if schedule.adult_fare is None or schedule.adult_fare == 0:
            # Use price if it exists, otherwise set a default
            if hasattr(schedule, 'price') and schedule.price:
                schedule.adult_fare = schedule.price
            else:
                schedule.adult_fare = Decimal('5000.00')  # Default fare
            schedule.save()


def reverse_migrate(apps, schema_editor):
    """Reverse migration - not needed but required"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0032_rename_executive_active_idx_salesrep_active_idx_and_more'),
    ]

    operations = [
        # Step 1: Migrate price to adult_fare for existing records
        migrations.RunPython(migrate_price_to_adult_fare, reverse_migrate),
        
        # Step 2: Make adult_fare non-nullable
        migrations.AlterField(
            model_name='schedule',
            name='adult_fare',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[MinValueValidator(0)],
                help_text='Fare for adults (12+ years)',
                verbose_name='adult fare (12+ years)'
            ),
        ),
        
        # Step 3: Remove price field from Schedule
        migrations.RemoveField(
            model_name='schedule',
            name='price',
        ),
        
        # Step 4: Remove base_price field from Route
        migrations.RemoveField(
            model_name='route',
            name='base_price',
        ),
    ]
