# Generated by Django 5.2.5 on 2025-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0033_auto_20251214_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='odwallet',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-calculated expiry date', null=True, verbose_name='expires at'),
        ),
        migrations.AddField(
            model_name='odwallet',
            name='expiry_days',
            field=models.IntegerField(default=0, help_text='Number of days after which wallet expires (0 = no expiry)', verbose_name='expiry days'),
        ),
        migrations.AddField(
            model_name='odwallet',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial balance when wallet was created/activated', max_digits=10, verbose_name='initial balance'),
        ),
        migrations.AlterField(
            model_name='odwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current balance (can be negative after expiry)', max_digits=10, verbose_name='balance'),
        ),
    ]
