# Generated by Django 5.2.5 on 2025-12-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0034_add_od_wallet_expiry_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_client_id_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrepresentative',
            new_name='salesrep_active_idx',
            old_name='executive_active_idx',
        ),
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sales_representative',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique agency identifier assigned on registration', max_length=20, null=True, unique=True, verbose_name='Agency ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Account approval status - user can login only after approval', verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sales_representative',
            field=models.ForeignKey(blank=True, help_text='Assigned sales representative for this agency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agencies', to='travels.salesrepresentative', verbose_name='Sales Representative'),
        ),
        migrations.AlterField(
            model_name='route',
            name='carrier_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='flight number'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transport_type',
            field=models.CharField(choices=[('flight', 'Flight')], default='flight', max_length=20, verbose_name='transport type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=20, verbose_name='user type'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['client_id'], name='userprofile_client_id_idx'),
        ),
        migrations.AlterModelTable(
            name='salesrepresentative',
            table='travels_executive',
        ),
    ]
