# Generated by Django 5.2.5 on 2025-12-18 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0035_move_approval_fields_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Passport Number')),
                ('nationality', models.CharField(default='Indian', max_length=100, verbose_name='Nationality')),
                ('country', models.CharField(choices=[('dubai', 'Dubai (UAE)'), ('oman', 'Oman'), ('bahrain', 'Bahrain'), ('qatar', 'Qatar'), ('azerbaijan', 'Azerbaijan'), ('uzbekistan', 'Uzbekistan'), ('vietnam', 'Vietnam'), ('cambodia', 'Cambodia'), ('russia', 'Russia')], max_length=50, verbose_name='Destination Country')),
                ('duration', models.CharField(help_text='e.g., 30 Days, 60 Days, 90 Days', max_length=50, verbose_name='Visa Duration')),
                ('visa_type', models.CharField(default='Tourist', help_text='e.g., Tourist, Business', max_length=50, verbose_name='Visa Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Currency')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100, verbose_name='Payment ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Application Status')),
                ('reference_id', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Reference ID')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests', verbose_name='Notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', verbose_name='Admin Notes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Visa Booking',
                'verbose_name_plural': 'Visa Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='visa_booking_status_idx'), models.Index(fields=['country', 'duration'], name='visa_booking_country_idx'), models.Index(fields=['payment_status'], name='visa_booking_payment_idx')],
            },
        ),
    ]
