# Generated by Django 5.2.5 on 2025-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0036_visabooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='visabooking',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='visabooking',
            name='passport_back',
            field=models.ImageField(blank=True, null=True, upload_to='visa_documents/passport_back/', verbose_name='Passport Back'),
        ),
        migrations.AddField(
            model_name='visabooking',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to='visa_documents/passport_front/', verbose_name='Passport Front'),
        ),
        migrations.AddField(
            model_name='visabooking',
            name='passport_size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visa_documents/passport_size/', verbose_name='Passport Size Photo'),
        ),
        migrations.AddField(
            model_name='visabooking',
            name='travel_date',
            field=models.DateField(blank=True, null=True, verbose_name='Travel Date'),
        ),
    ]
