# Generated by Django 5.2.5 on 2025-12-19 19:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0037_visabooking_address_visabooking_passport_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('date_change', 'Date Change'), ('name_correction', 'Name Correction'), ('flight_change', 'Flight Change'), ('seat_change', 'Seat Change'), ('cancellation', 'Cancellation Request'), ('refund', 'Refund Request'), ('other', 'Other')], default='other', max_length=20, verbose_name='Request Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('current_value', models.TextField(blank=True, help_text='Current date/name/details', verbose_name='Current Value')),
                ('requested_value', models.TextField(blank=True, help_text='New date/name/details', verbose_name='Requested Value')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Change')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('change_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Change Fee')),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Reference Number')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='travels.booking', verbose_name='Booking')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Booking Change Request',
                'verbose_name_plural': 'Booking Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='change_req_status_idx'), models.Index(fields=['booking', 'status'], name='change_req_booking_idx')],
            },
        ),
    ]
