# Generated by Django 5.2.5 on 2025-12-26 11:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0038_bookingchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalancewallet',
            name='max_balance',
            field=models.DecimalField(decimal_places=2, default=999999999, help_text='Maximum balance limit - set very high for no limit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum balance'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100, verbose_name='bank name')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='account holder name')),
                ('account_number', models.CharField(max_length=50, verbose_name='account number')),
                ('ifsc_code', models.CharField(max_length=20, verbose_name='IFSC code')),
                ('branch_name', models.CharField(blank=True, max_length=200, verbose_name='branch name')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=20, verbose_name='account type')),
                ('upi_id', models.CharField(blank=True, help_text='e.g., example@upi', max_length=100, null=True, verbose_name='UPI ID')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Upload UPI/Bank QR code for easy scanning', null=True, upload_to='bank_qr_codes/', verbose_name='QR code image')),
                ('is_active', models.BooleanField(default=True, help_text='Show this bank account to users', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which bank accounts are displayed', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['display_order', 'bank_name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='bank_account_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='reference ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('transaction_id', models.CharField(blank=True, help_text='UTR number or transaction reference', max_length=100, verbose_name='transaction ID')),
                ('proof_image', models.ImageField(help_text='Upload screenshot or photo of payment confirmation', upload_to='payment_proofs/', verbose_name='payment proof')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the payment', verbose_name='notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', verbose_name='admin notes')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('bank_account', models.ForeignKey(blank=True, help_text='Bank account where payment was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_uploads', to='travels.bankaccount', verbose_name='bank account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_uploads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_uploads', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'Payment Upload Request',
                'verbose_name_plural': 'Payment Upload Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='payment_upload_user_idx'), models.Index(fields=['status', 'created_at'], name='payment_upload_status_idx')],
            },
        ),
    ]
