# Generated by Django 5.2.5 on 2025-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0039_alter_cashbalancewallet_max_balance_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=255, verbose_name='email'),
        ),
    ]
