# Generated by Django 5.2.5 on 2025-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0040_salesrepresentative_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='flight_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('via', 'Via/Connecting')], default='direct', help_text='Direct flight or connecting flight via layover', max_length=20, verbose_name='flight type'),
        ),
        migrations.AddField(
            model_name='route',
            name='layover_airport',
            field=models.CharField(blank=True, help_text='Airport code/name for layover (e.g., DXB, Dubai). Required for via flights.', max_length=100, verbose_name='layover airport'),
        ),
        migrations.AddField(
            model_name='route',
            name='layover_duration',
            field=models.DurationField(blank=True, help_text='Duration of layover (e.g., 2:30:00 for 2h 30m). Required for via flights.', null=True, verbose_name='layover duration'),
        ),
    ]
