# Generated by Django 5.2.5 on 2025-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0041_route_flight_type_route_layover_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuploadrequest',
            name='payment_method',
            field=models.CharField(choices=[('net_banking', 'Net Banking'), ('upi', 'UPI / QR Code'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('wallet', 'Digital Wallet'), ('neft_rtgs', 'NEFT / RTGS'), ('imps', 'IMPS'), ('cheque', 'Cheque'), ('cash', 'Cash Deposit'), ('other', 'Other')], default='upi', help_text='Method used for payment', max_length=20, verbose_name='payment method'),
        ),
    ]
