# Generated by Django 5.2.5 on 2026-01-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0042_paymentuploadrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Designates whether this user account is verified', verbose_name='verified'),
        ),
    ]
