"""
Django settings for Travel_agency project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-t%iz5uu+9-^(kl+^s4=35odc331$*hg5qsa1*plz!h@q4$be(=')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG = True for local development, False for production
DEBUG = os.environ.get('DEBUG', 'True') == 'True'  # Default to True for development

# Production domain and IP
DOMAIN_NAME = 'safarzonetravels.com'
SERVER_IP = '165.232.178.54'

ALLOWED_HOSTS = [
    DOMAIN_NAME,
    'www.' + DOMAIN_NAME,
    SERVER_IP,
    'localhost',
    '127.0.0.1',
]

# CSRF Trusted Origins - Allow Easebuzz payment gateway callbacks
CSRF_TRUSTED_ORIGINS = [
    'https://pay.easebuzz.in',
    'https://testpay.easebuzz.in',
    f'https://{DOMAIN_NAME}',
    f'https://www.{DOMAIN_NAME}',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'travels.apps.TravelsConfig',
    'whitenoise.runserver_nostatic',  # For production static file serving
]

# Custom user model
AUTH_USER_MODEL = 'travels.User'

# Media files (user uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = 'Travel_agency.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'travels.context_processors.wallet_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Travel_agency.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'homepage'

# Easebuzz Payment Gateway Settings
# Get your keys from Easebuzz dashboard after approval
# LIVE CREDENTIALS (Production)
EASEBUZZ_MERCHANT_KEY = os.environ.get('EASEBUZZ_MERCHANT_KEY', 'VMZA9Y0A3K')
EASEBUZZ_MERCHANT_SALT = os.environ.get('EASEBUZZ_MERCHANT_SALT', '12SZXDDTMA')
EASEBUZZ_ENV = os.environ.get('EASEBUZZ_ENV', 'prod')  # 'prod' for production, 'test' for test
# Easebuzz API URLs
# IMPORTANT: Try these URLs one by one if getting 404 error:
# Option 1: https://testpay.easebuzz.in/payment/initiate
# Option 2: https://testpay.easebuzz.in/
# Option 3: https://pay.easebuzz.in/payment/initiate (if merchant key is for production)
# 
# For test environment: https://testpay.easebuzz.in/payment/initiate
# For production: https://pay.easebuzz.in/payment/initiate
# 
# IMPORTANT: Merchant key must match the environment (test/production)
# If merchant key is for test, use test URL. If for production, use production URL.
# 
# If still getting 404, contact Easebuzz support to verify:
# 1. Correct payment URL for your merchant account
# 2. Whether merchant key is for test or production
# 3. Dashboard configuration settings
# Try base URL first - Easebuzz might not use /payment/initiate endpoint
# If this doesn't work, try: https://testpay.easebuzz.in/payment/initiate
EASEBUZZ_PAYMENT_URL = os.environ.get('EASEBUZZ_PAYMENT_URL', 'https://testpay.easebuzz.in/')
EASEBUZZ_STATUS_URL = os.environ.get('EASEBUZZ_STATUS_URL', 'https://testpay.easebuzz.in/payment/status')

# Email Configuration
# Using Brevo HTTP API (not SMTP) - DigitalOcean blocks ALL SMTP ports
# Brevo API uses HTTP/HTTPS (ports 80/443) which are NOT blocked
EMAIL_BACKEND = 'travels.email_backend.BrevoAPIEmailBackend'  # Custom backend using Brevo API

# GoDaddy SMTP Settings (Primary - will try port 2525 first)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtpout.secureserver.net')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '2525'))  # Try 2525 first (not blocked)
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'

# GoDaddy email credentials
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'noreply@safarzonetravels.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'SafarZone@123')

# Brevo (Sendinblue) API Configuration - FREE 300 emails/day
# Using HTTP API instead of SMTP (DigitalOcean blocks ALL SMTP ports)
# IMPORTANT: Get API key from: https://app.brevo.com/settings/keys/api
# DO NOT use SMTP key - API key is different!
# For production, set BREVO_API_KEY as environment variable on server!
# Brevo API key - Get from environment variable (set on server)
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')  # Brevo API key (from API keys page, NOT SMTP)
# IMPORTANT: Set BREVO_API_KEY as environment variable on server!
# Do NOT hardcode API keys in code - use environment variables
BREVO_SMTP_KEY = os.environ.get('BREVO_SMTP_KEY', '')  # Fallback to SMTP key if API key not set (not needed if using API key)
BREVO_SMTP_USER = os.environ.get('BREVO_SMTP_USER', 'noreply@safarzonetravels.com')  # Brevo account email (for reference)
DEFAULT_FROM_EMAIL_NAME = 'Safar Zone Travels'  # Sender name for emails

# FREE Gmail SMTP (Fallback - 100% FREE, 500 emails/day)
# Setup: https://myaccount.google.com/apppasswords
GMAIL_USER = os.environ.get('GMAIL_USER', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')

# FREE Outlook SMTP (Alternative Fallback - 100% FREE, 300 emails/day)
OUTLOOK_USER = os.environ.get('OUTLOOK_USER', '')
OUTLOOK_PASSWORD = os.environ.get('OUTLOOK_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Email timeout (important for production)
EMAIL_TIMEOUT = 30  # seconds

# Server email for error reporting
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ADMINS = [
    ('Admin', os.environ.get('ADMIN_EMAIL', 'admin@safarzonetravels.com')),
]

# Logging configuration for email debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'email.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django.core.mail': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'travels.views': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)